server:
  port: 9090
spring:
  datasource:
    username: root
    password: "!@#mysql"
    url: jdbc:mysql://localhost:3306/db_detection
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
