/*
 Navicat Premium Data Transfer

 Source Server         : mysql01
 Source Server Type    : MySQL
 Source Server Version : 80029
 Source Host           : localhost:3306
 Source Schema         : db_detection

 Target Server Type    : MySQL
 Target Server Version : 80029
 File Encoding         : 65001

 Date: 27/03/2024 22:17:32
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for template_info
-- ----------------------------
DROP TABLE IF EXISTS `template_info`;
CREATE TABLE `template_info`  (
  `template_id` int NOT NULL COMMENT '绑定的模板id',
  `soh_flag` int NOT NULL COMMENT '“诚信声明”标志位，0无，1有',
  `soh_seq` int NULL DEFAULT NULL COMMENT '次序，默认为1',
  `soh_content` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '诚信说明内容',
  `soh_h_font_type` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '\"诚信声明\"标题字体类别',
  `soh_h_font_english_type` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '西文字体类别',
  `soh_h_font_sz` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '字体大小',
  `soh_h_jc` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '对齐方式left，right，center，\"jc\" 表示 \"justification\"',
  `soh_h_bold` int NULL DEFAULT NULL COMMENT '字体加粗，0无，1有',
  `soh_h_afterline` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '段后间隔，100为1行',
  `soh_h_beforeline` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '段前间隔，100为1行',
  `soh_h_line` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '段间距，240为1行，lineRule需要设置为auto',
  `soh_p_font_type` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '\"诚信声明\"段落字体类别',
  `soh_p_font_type_english` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '西文字体类别',
  `soh_p_font_sz` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '字体大小',
  `soh_p_ind` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '首行缩进',
  `soh_p_line` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '段间距',
  `soh_p_bold` int NULL DEFAULT NULL COMMENT '段落正文是否加粗，0无1有',
  `aoc_flag` int NULL DEFAULT NULL COMMENT '中文摘要是否有',
  `aoc_seq` int NULL DEFAULT NULL COMMENT '中文摘要次序',
  `aoc_prefixFont` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '前置词字体',
  `aoc_isPrefixBold` int NULL DEFAULT NULL COMMENT '前置词是否加粗',
  `aoc_recommendedMaxContentLength` int NULL DEFAULT NULL COMMENT '摘要的推荐最大字数',
  `aoc_recommendedMaxKeywordsCount` int NULL DEFAULT NULL COMMENT '关键词的推荐最大个数',
  `aoc_h_font_type` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '标题字体类别',
  `aoc_h_font_english_type` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '西文字体类别',
  `aoc_h_font_sz` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '字体大小',
  `aoc_h_jc` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '对齐方式left，right，center，\"jc\" 表示 \"justification\"',
  `aoc_h_bold` int NULL DEFAULT NULL COMMENT '字体加粗，0无，1有',
  `aoc_h_afterline` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '段后间隔，100为1行',
  `aoc_h_beforeline` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '段前间隔，100为1行',
  `aoc_h_line` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '段间距，240为1行，lineRule需要设置为auto',
  `aoc_p_font_type` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '段落字体类别',
  `aoc_p_font_type_english` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '西文字体类别',
  `aoc_p_font_sz` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '字体大小',
  `aoc_p_ind` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '首行缩进',
  `aoc_p_line` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '段间距',
  `aoc_p_bold` int NULL DEFAULT NULL COMMENT '段落正文是否加粗，0无1有',
  `aoe_flag` int NULL DEFAULT NULL COMMENT '英文摘要是否有',
  `aoe_seq` int NULL DEFAULT NULL COMMENT '英文摘要次序',
  `aoe_prefixFont` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '前置词字体',
  `aoe_isPrefixBold` int NULL DEFAULT NULL COMMENT '前置词是否加粗',
  `aoe_recommendedMaxContentLength` int NULL DEFAULT NULL COMMENT '摘要的推荐最大字数',
  `aoe_recommendedMaxKeywordsCount` int NULL DEFAULT NULL COMMENT '关键词的推荐最大个数',
  `aoe_h_font_type` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '标题字体类别',
  `aoe_h_font_english_type` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '西文字体类别',
  `aoe_h_font_sz` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '字体大小',
  `aoe_h_jc` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '对齐方式left，right，center，\"jc\" 表示 \"justification\"',
  `aoe_h_bold` int NULL DEFAULT NULL COMMENT '字体加粗，0无，1有',
  `aoe_h_afterline` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '段后间隔，100为1行',
  `aoe_h_beforeline` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '段前间隔，100为1行',
  `aoe_h_line` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '段间距，240为1行，lineRule需要设置为auto',
  `aoe_p_font_type` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '段落字体类别',
  `aoe_p_font_type_english` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '西文字体类别',
  `aoe_p_font_sz` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '字体大小',
  `aoe_p_ind` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '首行缩进',
  `aoe_p_line` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '段间距',
  `aoe_p_bold` int NULL DEFAULT NULL COMMENT '段落正文是否加粗，0无1有',
  `catalogue_flag` int NULL DEFAULT NULL COMMENT '目录是否有',
  `catalogue_seq` int NULL DEFAULT NULL COMMENT '目录次序',
  `catalogue_h_font_type` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '标题字体类别',
  `catalogue_h_font_english_type` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '西文字体类别',
  `catalogue_h_font_sz` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '字体大小',
  `catalogue_h_jc` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '对齐方式left，right，center，\"jc\" 表示 \"justification\"',
  `catalogue_h_bold` int NULL DEFAULT NULL COMMENT '字体加粗，0无，1有',
  `catalogue_h_afterline` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '段后间隔，100为1行',
  `catalogue_h_beforeline` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '段前间隔，100为1行',
  `catalogue_h_line` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '段间距，240为1行，lineRule需要设置为auto',
  `mainbody_flag` int NULL DEFAULT NULL COMMENT '绪论和正文是否有',
  `mainbody_seq` int NULL DEFAULT NULL COMMENT '绪论和正文次序',
  `mainbody_h1_font_type` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '标题字体类别',
  `mainbody_h1_font_english_type` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '西文字体类别',
  `mainbody_h1_font_sz` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '字体大小',
  `mainbody_h1_jc` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '对齐方式left，right，center，\"jc\" 表示 \"justification\"',
  `mainbody_h1_bold` int NULL DEFAULT NULL COMMENT '字体加粗，0无，1有',
  `mainbody_h1_afterline` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '段后间隔，100为1行',
  `mainbody_h1_beforeline` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '段前间隔，100为1行',
  `mainbody_h1_line` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '段间距，240为1行，lineRule需要设置为auto',
  `mainbody_h2_font_type` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '标题字体类别',
  `mainbody_h2_font_english_type` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '西文字体类别',
  `mainbody_h2_font_sz` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '字体大小',
  `mainbody_h2_jc` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '对齐方式left，right，center，\"jc\" 表示 \"justification\"',
  `mainbody_h2_bold` int NULL DEFAULT NULL COMMENT '字体加粗，0无，1有',
  `mainbody_h2_afterline` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '段后间隔，100为1行',
  `mainbody_h2_beforeline` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '段前间隔，100为1行',
  `mainbody_h2_line` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '段间距，240为1行，lineRule需要设置为auto',
  `mainbody_h3_font_type` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '标题字体类别',
  `mainbody_h3_font_english_type` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '西文字体类别',
  `mainbody_h3_font_sz` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '字体大小',
  `mainbody_h3_jc` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '对齐方式left，right，center，\"jc\" 表示 \"justification\"',
  `mainbody_h3_bold` int NULL DEFAULT NULL COMMENT '字体加粗，0无，1有',
  `mainbody_h3_afterline` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '段后间隔，100为1行',
  `mainbody_h3_beforeline` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '段前间隔，100为1行',
  `mainbody_h3_line` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '段间距，240为1行，lineRule需要设置为auto',
  `mainbody_p_font_type` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '段落字体类别',
  `mainbody_p_font_type_english` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '西文字体类别',
  `mainbody_p_font_sz` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '字体大小',
  `mainbody_p_ind` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '首行缩进',
  `mainbody_p_line` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '段间距',
  `mainbody_p_bold` int NULL DEFAULT NULL COMMENT '段落正文是否加粗，0无1有',
  `conclusion_flag` int NULL DEFAULT NULL COMMENT '结论是否有',
  `conclusion_seq` int NULL DEFAULT NULL COMMENT '结论次序',
  `conclusion_recommendedMaxContentLength` int NULL DEFAULT NULL COMMENT '推荐的结论最大字数',
  `conclusion_h_font_type` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '标题字体类别',
  `conclusion_h_font_english_type` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '西文字体类别',
  `conclusion_h_font_sz` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '字体大小',
  `conclusion_h_jc` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '对齐方式left，right，center，\"jc\" 表示 \"justification\"',
  `conclusion_h_bold` int NULL DEFAULT NULL COMMENT '字体加粗，0无，1有',
  `conclusion_h_afterline` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '段后间隔，100为1行',
  `conclusion_h_beforeline` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '段前间隔，100为1行',
  `conclusion_h_line` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '段间距，240为1行，lineRule需要设置为auto',
  `conclusion_p_font_type` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '段落字体类别',
  `conclusion_p_font_type_english` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '西文字体类别',
  `conclusion_p_font_sz` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '字体大小',
  `conclusion_p_ind` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '首行缩进',
  `conclusion_p_line` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '段间距',
  `conclusion_p_bold` int NULL DEFAULT NULL COMMENT '段落正文是否加粗，0无1有',
  `thanks_flag` int NULL DEFAULT NULL COMMENT '致谢是否有',
  `thanks_seq` int NULL DEFAULT NULL COMMENT '致谢次序',
  `thanks_recommendedMaxContentLength` int NULL DEFAULT NULL COMMENT '推荐的致谢最大字数',
  `thanks_h_font_type` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '标题字体类别',
  `thanks_h_font_english_type` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '西文字体类别',
  `thanks_h_font_sz` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '字体大小',
  `thanks_h_jc` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '对齐方式left，right，center，\"jc\" 表示 \"justification\"',
  `thanks_h_bold` int NULL DEFAULT NULL COMMENT '字体加粗，0无，1有',
  `thanks_h_afterline` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '段后间隔，100为1行',
  `thanks_h_beforeline` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '段前间隔，100为1行',
  `thanks_h_line` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '段间距，240为1行，lineRule需要设置为auto',
  `thanks_p_font_type` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '段落字体类别',
  `thanks_p_font_type_english` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '西文字体类别',
  `thanks_p_font_sz` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '字体大小',
  `thanks_p_ind` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '首行缩进',
  `thanks_p_line` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '段间距',
  `thanks_p_bold` int NULL DEFAULT NULL COMMENT '段落正文是否加粗，0无1有', 
  `references_flag` int NULL DEFAULT NULL COMMENT '参考文献是否有',
  `references_seq` int NULL DEFAULT NULL COMMENT '参考文献次序',
  `references_recommendedMinCount` int NULL DEFAULT NULL COMMENT '推荐的参考文献最少条数',
  `references_h_font_type` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '标题字体类别',
  `references_h_font_english_type` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '西文字体类别',
  `references_h_font_sz` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '字体大小',
  `references_h_jc` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '对齐方式left，right，center，\"jc\" 表示 \"justification\"',
  `references_h_bold` int NULL DEFAULT NULL COMMENT '字体加粗，0无，1有',
  `references_h_afterline` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '段后间隔，100为1行',
  `references_h_beforeline` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '段前间隔，100为1行',
  `references_h_line` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '段间距，240为1行，lineRule需要设置为auto',
  `references_p_font_type` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '段落字体类别',
  `references_p_font_type_english` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '西文字体类别',
  `references_p_font_sz` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '字体大小',
  `references_p_ind` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '首行缩进',
  `references_p_line` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '段间距',
  `references_p_bold` int NULL DEFAULT NULL COMMENT '段落正文是否加粗，0无1有', 
  `caption_fontName` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '图表注释字体',
  `caption_fontEnglishName` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '图表注释英文字体',
  `caption_fontSize` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '图表注释字号',
  `caption_picSzWidthMin` double NULL DEFAULT NULL COMMENT '图片最小宽度',
  `caption_picSzWidthMax` double NULL DEFAULT NULL COMMENT '图片最大宽度',
  `caption_picSzHeightMin` double NULL DEFAULT NULL COMMENT '图片最小高度',
  `caption_picSzHeightMax` double NULL DEFAULT NULL COMMENT '图片最大高度',
  `caption_recommendNum` int NULL DEFAULT NULL COMMENT '推荐的图表数量，这个数量是最小值，可以多于这个数量。',
  `pageSetting_headerContent1` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '页眉内容1',
  `pageSetting_headerContent2` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '页眉内容2',
  `pageSetting_topMargin` double NULL DEFAULT NULL COMMENT '页上边距',
  `pageSetting_bottomMargin` double NULL DEFAULT NULL COMMENT '页下边距',
  `pageSetting_leftMargin` double NULL DEFAULT NULL COMMENT '页左边距',
  `pageSetting_rightMargin` double NULL DEFAULT NULL COMMENT '页右边距',
  `pageSetting_headerMargin` double NULL DEFAULT NULL COMMENT '页眉边距',
  `pageSetting_footerMargin` double NULL DEFAULT NULL COMMENT '页脚边距',
  `pageSetting_oddEvenPage` int NULL DEFAULT NULL COMMENT '奇偶页设置，0无，1有'
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = Dynamic;

SET FOREIGN_KEY_CHECKS = 1;
